[language-server]
expert = { command = "/Users/pawel/projects/elixir/expert/apps/expert/burrito_out/expert_darwin_arm64", args = ["--stdio"] }

[[language]]
name = "elixir"
language-servers = [ "expert" ]
text-width = 100

[[language]]
name = "heex"
language-servers = [ "expert" ]
text-width = 100

[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}
