gui:
  theme:
    selectedLineBgColor:
      - '#404c51'
    selectedRangeBgColor:
      - '#404c51'
  showFileTree: false
os:
  edit: 'hx {{filename}}'
  editAtLine: 'hx {{filename}}:{{line}}'
  editAtLineAndWait: 'hx {{filename}}:{{line}}'
  editInTerminal: true
promptToReturnFromSubprocess: false
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
      # externalDiffCommand: difft --color=always --display=inline
  overrideGpg: true
