[opener]
glow = [
	{ run = 'glow -p %s', block = true, for = "unix", desc = "Glow" },
]

[open]
prepend_rules = [
	{ url = "*.log", use = [ "edit" ] },
	{ url = "*.md",  use = [ "glow", "edit", "reveal" ] },
]
